bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get    '/',        to: 'home#index'
    resources :users
    resources :profile, only: %i[index update] do
      collection do
        get 'password'
        put 'update_password'
      end
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin::BaseController < ApplicationController
  include Pagy::Backend
  layout 'admin/base'

  before_action :set_time_zone
  before_action :authenticate_admin!

  def set_time_zone
    Time.zone = cookies[:time_zone]
  end
end

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_flash_messages.html.erb
<% message = notice || alert %>

<% if message.present? %>
  <div class="position-fixed start-50 translate-middle-x" style="z-index: 1030; top: 8rem;">
    <div class="toast hide text-center text-white bg-dark border-0" data-controller="flash-message">
      <div class="toast-body">
        <%= message %>
      </div>
    </div>
  </div>
<% end %>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_footer.html.erb
<footer class="footer footer-transparent d-print-none">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item"><a href="./docs/index.html" class="link-secondary">Documentation</a></li>
          <li class="list-inline-item"><a href="./license.html" class="link-secondary">License</a></li>
          <li class="list-inline-item"><a href="https://github.com/tabler/tabler" target="_blank" class="link-secondary" rel="noopener">Source code</a></li>
          <li class="list-inline-item">
            <a href="https://github.com/sponsors/codecalm" target="_blank" class="link-secondary" rel="noopener">
              <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink icon-filled icon-inline" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" /></svg>
              Sponsor
            </a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            Copyright &copy; 2022
            <a href="." class="link-secondary">Tabler</a>.
            All rights reserved.
          </li>
          <li class="list-inline-item">
            <a href="./changelog.html" class="link-secondary" rel="noopener">
              v1.0.0-beta6
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_javascript_tags.html.erb
<!-- Tabler Core -->
<script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta11/dist/js/tabler.min.js"></script>

<!-- Time zone cookie -->
<script type="module">
  import cookies from "https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.mjs"
  const { timeZone } = new Intl.DateTimeFormat().resolvedOptions()
  cookies.set("time_zone", timeZone, { expires: 365 })
</script>

<!-- Data confirm -->
<script type="module">
  document.addEventListener("click", (event) => {
    if (!event.target.matches("[data-confirm]")) return
    if (!window.confirm(event.target.dataset["confirm"])) event.preventDefault()
  })
</script>

<!-- Stimulus controllers -->
<script type="module">
  import { Application, Controller } from "https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.1.0/dist/stimulus.min.js"
  window.Stimulus = Application.start()

  Stimulus.register("flash-message", class extends Controller {
    connect() {
      new bootstrap.Toast(this.element).show()
    }
  })
</script>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_page_header.html.erb
<div class="container-xl">
  <div class="page-header">
    <div class="row align-items-center">
      <%= yield %>
    </div>
  </div>
</div>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_page_header_actions.html.erb
<div class="col-auto">
  <div class="btn-list">
    <%= yield %>
  </div>
</div>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_page_header_breadcrumb.html.erb
<%= content_for :title, title %>

<div class="col">
  <div class="mb-1">
    <ol class="breadcrumb" aria-label="breadcrumbs">
      <%= yield %>
    </ol>
  </div>
  <h1 class="page-title">
    <span class="text-truncate"><%= title %></span>
  </h1>
</div>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, link_extra: 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager" class="pagy-bootstrap-nav d-inline-block" role="navigation">
<%#                            -%>  <ul class="pagination m-0">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_primary_navbar.html.erb
<header class="navbar navbar-expand-md navbar-light d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <%= link_to admin_path do %>
        <%= image_tag "admin/logo.svg", width: 110, height: 32, alt: "Tabler", class: "navbar-brand-image" %>
      <% end %>
    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <a href="?theme=light" class="nav-link px-0 hide-theme-light" title="Enable light mode" data-bs-toggle="tooltip" data-bs-placement="bottom">
        <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><circle cx="12" cy="12" r="4" /><path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7" /></svg>
      </a>
      <div class="nav-item dropdown d-none d-md-flex me-3">
        <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1" aria-label="Show notifications">
          <!-- Download SVG icon from http://tabler-icons.io/i/bell -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" /><path d="M9 17v1a3 3 0 0 0 6 0v-1" /></svg>
          <span class="badge bg-red"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-end dropdown-menu-card">
          <div class="card">
            <div class="card-body">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad amet consectetur exercitationem fugiat in ipsa ipsum, natus odio quidem quod repudiandae sapiente. Amet debitis et magni maxime necessitatibus ullam.
            </div>
          </div>
        </div>
      </div>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
          <span class="avatar avatar-sm" style="background-image: url(<%= current_admin.avatar.url %>)"></span>
          <div class="d-none d-xl-block ps-2">
            <div><%= current_admin.name %></div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
          <a href="#" class="dropdown-item">Set status</a>
          <%= link_to 'Profile & account', admin_profile_index_path, class: 'dropdown-item' %>
          <a href="#" class="dropdown-item">Feedback</a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">Settings</a>
          <%= button_to "Logout", destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    </div>
  </div>
</header>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_secondary_navbar.html.erb
<div class="navbar-expand-md">
  <div class="collapse navbar-collapse" id="navbar-menu">
    <div class="navbar navbar-light">
      <div class="container-xl">
        <ul class="navbar-nav">
          <li class="nav-item <%= active_nav_item 'admin/home' %>">
            <%= link_to admin_path, class: "nav-link" do %>
              <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="5 12 3 12 12 3 21 12 19 12" /><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" /><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" /></svg>
              </span>
              <span class="nav-link-title">
                Dashboard
              </span>
            <% end %>
          </li>
          <li class="nav-item <%= active_nav_item 'admin/users' %>">
            <%= link_to admin_users_path, class: "nav-link" do %>
              <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><circle cx="9" cy="7" r="4"></circle><path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path><path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path></svg>
              </span>
              <span class="nav-link-title">
                Users
              </span>
            <% end %>
          </li>
        </ul>
        <div class="my-2 my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-last"></div>
      </div>
    </div>
  </div>
</div>

bundle/pkg-ready/templates/ruby/ruby-on-rails-boilerplate-template/app/views/admin/base/_stylesheet_link_tags.html.erb
<!-- Tabler Core -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta11/dist/css/tabler.min.css">

<!-- Customize tabler here -->

<style>body {
  --tblr-body-bg: #f5f7fb;
}</style>